### ISSUE TITLE
Portals disappearing from dropdown

### ISSUE THREAD

**Issue by DasNiels** [sweetgiorni/AnyPortal#2]
Please note: this is a duplicate of my bug report posted on nexusmods, your description stated to post bugs here so here it is :P

So I logged in today with most of my portals missing from the dropdown.

I checked the mod, saw an update so updated both client and server to the latest version, and still most of the portals are missing from the dropdown.

As of right now I have no idea how to fix this.

I put both files (anyportal and AnyPortal.dll) in BepInEx\plugins\AnyPortal.

**Comment by sweetgiorni** [comment]
Are the missing petals all relatively far away?

**Comment by DasNiels** [comment]
Yeah they are actually. Although the ones that do work (1 at the moment) is also quite far away(2032 distance). some that aren't showing are closer than that.

**Comment by sweetgiorni** [comment]
Well I can't recreate the issue, but I see there is another method for getting world objects. Can you try this patch and tell me if it helps?

[anyportal.zip](https://github.com/sweetgiorni/AnyPortal/files/6056762/anyportal.zip)

**Comment by DasNiels** [comment]
Just tested it, didn't change anything unfortunately.

Not sure if it makes a difference but the portals that I have were placed before I installed this mod.
Although, I did place a portal before restarting the server(and testing your change) and that portal also doesn't show up anymore on the list.

The only portal that appears to be visible is the one I have placed at the sacrificial stones(spawn point) and the one at my base where I spawn after logging in.

**Comment by gOOvER** [comment]
I have the same problem; after reconnect only 2 Portals are shown. When i go to the not shown portals, all will be shown, when i use them, but after relogg they are gone. Looks like, the list will not be saved

**Comment by DasNiels** [comment]
One more update, in the server-log I've noticed this message popping up: https://github.com/sweetgiorni/AnyPortal/blob/master/AnyPortal.cs#L205

Not sure if that's supposed to happen? or what I should do to fix it if it's not supposed to be there.

**Comment by gOOvER** [comment]
Before relogg:

![valheim_6FcoBqHHra](https://user-images.githubusercontent.com/116325/109420628-ce3b8680-79d3-11eb-9999-1efbc9b2835d.png)

After relogg:

![valheim_3JxOBJ26n6](https://user-images.githubusercontent.com/116325/109420636-dbf10c00-79d3-11eb-8e7c-acd7f85224d4.png)

**Comment by DasNiels** [comment]
Just started the game in single player without dedi server. as in: start game -> select world -> play(not even starting a server).

All teleporters show up properly when playing single player.

Whatever is causing the issue, it must be server-side/multiplayer related.

**Comment by sweetgiorni** [comment]
Should be fixed in 1.0.3 which was just published. Make sure you updated both client and server.

@DasNiels Regarding this:
""Connect portals is running - it's supposed to be disabled!?!?""
Do you have the latest version installed on your server? It was present in 1.0.0.0, but should be gone in 1.0.1+

**Comment by DasNiels** [comment]
No clue, I downloaded the latest version and everything works fine now though :), thanks!

One sidenote: the scrollbar is quite slow, not sure if that's something you can fix but I have to scroll 2 - 3x for 1 extra entry to show up in the dropdown. Feels like it should be 1 scroll to go down 2 - 3 entries.

**Comment by gOOvER** [comment]
> Should be fixed in 1.0.3 which was just published. Make sure you updated both client and server.
> 
> @DasNiels Regarding this:
> ""Connect portals is running - it's supposed to be disabled!?!?""
> Do you have the latest version installed on your server? It was present in 1.0.0.0, but should be gone in 1.0.1+

1.0.3 works :)

**Comment by sweetgiorni** [comment]
> No clue, I downloaded the latest version and everything works fine now though :), thanks!
> 
> One sidenote: the scrollbar is quite slow, not sure if that's something you can fix but I have to scroll 2 - 3x for 1 extra entry to show up in the dropdown. Feels like it should be 1 scroll to go down 2 - 3 entries.

That should be fixed in 1.0.1. Make sure you update the assetbundle file "anyportal" in addition to the dll. That's where the dropdown prefab is located.
