### ISSUE TITLE
Retain Coords After Closing Valheim

### ISSUE THREAD

**Issue by tedrock** [sweetgiorni/AnyPortal#7]
Any plans on making it so your location data is preserved between sessions? I have a habit of going home before I quit, when I log back in I can't teleport back to where my recall point was.

**Comment by sweetgiorni** [comment]
If you're talking about saving the portal selected in the dropdown, that should already be working. If it isn't working for you, please create a new ticket and fill out the bug report template.

**Comment by tedrock** [comment]
I apologize, I posted this on the wrong portal mod, I use a few. Your mod is great btw :)
