### ISSUE TITLE
Drop down menu for portal not present in Linux

### ISSUE THREAD

**Issue by feydreva** [sweetgiorni/AnyPortal#9]
Drop down menu not present

When using the portal, no drop down menu is present.
When pressing e, it open the box to rename the current portal, but no drop down menu

I am running the Linux cleint of Valheim.
BepInEx is installled (5.4.8.0)
Other mods are working properly

**Screenshots**
![image](https://user-images.githubusercontent.com/3083670/110329450-e2f3cc00-801c-11eb-821b-ade4fc423abe.png)
![image](https://user-images.githubusercontent.com/3083670/110329479-eedf8e00-801c-11eb-9acc-128ab5ba799b.png)

### Game version and environment

**Game client version (found in the bottom right of the Valheim main menu**
v 0.147.3

**After reproducing the issue, please attach the BepInEx game log from Valheim/BepInEx/LogOutput.log**

[Error  : Unity Log] AnyPortal: Tried to access the AssetBundle before loading it!
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AnyPortal.AnyPortal+PortalInteractPatch.Postfix (TeleportWorld __instance, ZNetView& ___m_nview, System.Boolean& __result) (at <e9ec368696fe4dc9823f023eba55d014>:0)
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::Interact>(TeleportWorld,Humanoid,bool)
(wrapper dynamic-method) Player.DMD<Player::Interact>(Player,UnityEngine.GameObject,bool)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Does the issue occur in single-player or multiplayer? You can also check "Both" if you've reproduced the issue in both game modes**
- [] Single-player
- [X ] Multiplayer
- [ ] Both

**If the issue occurs in multiplayer, is the server a "local" server started through the in-game menu, or is it a headless server (like installing the "Valheim Dedicated Server" in Steam or using a server hosting service)**
- [] N/A
- [ ] In-game server
- [X] Headless server

**If you are using a headless server, please reproduce the issue and then attach the BepInEx game log from ValheimServer/BepInEx/LogOutput.log**

**If you are using a headless server, is it being hosted on a  Windows machine or a Linux machine?**
- [ ] Windows
- [ ] Linux

**Comment by sweetgiorni** [comment]
Hmm. I didn't know there was a Linux release for the game client. I can build a version that supports Linux if you want to beta test? I don't feel like setting up a VM

**Comment by feydreva** [comment]
Yes, Valheim as a native Linux Client.
BepInEx as Linux support.
And mosty mod works well, like the one for the extra amor slot, the Potion slot, Share map, Auto gardening, smart container, etc etc.

Only issue I have is with Auto Portal.
my friend all have this one, and now I am kinda stuck if it does'nt work on linux (as now, the is not fix portal linked)

Yes I am ready to test it, and provide feedback and logs as needed.

**Comment by TimSC** [comment]
I have the same issue. Is this related to the forum comment about broken drop down menu https://forums.nexusmods.com/index.php?/topic/9704258-anyportal/page-9#entry92171248 ?

**Comment by sweetgiorni** [comment]
Fixed in v2.0.0
